lint:
    stage: test
    image: node:alpine
    script: 
        - npx eslint .

test_build:
    stage: test
    image: node:alpine
    script:
        - apk add alpine-sdk python cargo git bash
        - npm i --only=production
