version: "3"

services: 
    db:
        image: rethinkdb
        volumes: 
            - ./rethinkdb_data:/data
        restart: always
        networks: [internal_net]
    bot:
        build: "."
        environment: 
            NODE_ENV: production
        ports:
            - "127.0.0.1:8826:8826"
        restart: always
        depends_on: [db]
        networks: [internal_net, external_net]

networks:
    internal_net:
        internal: true
    external_net:
