version: "3"

services: 
    db:
        image: rethinkdb
        volumes: 
            - ./rethinkdb_data:/data
        restart: always
        networks: [external_net]
    bot:
        build: "."
        environment: 
            NODE_ENV: production
        ports:
            - "127.0.0.1:8826:8826"
        volumes:
            - ./config.js:/app/config.js
        restart: always
        depends_on: [db]
        networks: [external_net]

networks:
    external_net:
