version: "3"

services: 
    db:
        image: rethinkdb
        internal: true
        volumes: 
            - ./rethinkdb_data:/data
    bot:
        build: "."
        environment: 
            NODE_ENV: production
        ports:
            - "8826"