name: Check linting

on:
  push:
    branches-ignore:
      dependabot/**
  pull_request:
    branches-ignore:
      dependabot/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ">=10.0.0"
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: Run the tests
      run: ./travis/test.sh
      env:
        CI: true
      if: github.actor != 'tt-bot' && github.actor != 'github-actions'
    - name: Fix linting issues
      run: ./travis/fixlint.sh
      env:
        CURRENT_BRANCH: ${{ github.ref }}
        CURRENT_COMMIT: ${{ github.sha }}
        COMMIT_AUTHOR: ${{ github.actor }}
        GIT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: true
        CURRENT_REPO: ${{ github.repository }}
      if: github.event_name != 'pull_request' && failed()
